### ISSUE TITLE
When can I get your code ?

### ISSUE THREAD

**Issue by locomotive-crypto** [TRUST-TUDa/SAFELearn#1]
I have read your paper:https://eprint.iacr.org/2021/386.pdf.

Now, I find this link from your paper for your code. 

However, I get nothing. 

When can I get it?

**Comment by Nozdormu-Timer** [comment]
the same question

**Comment by phillip-rieger** [comment]
We will upload the code by mid of June. Sorry for the delay!

**Comment by phillip-rieger** [comment]
Hi, sorry for the delay!
The code is now uploaded.
